### ISSUE TITLE
ON HOLD - Fix number above nav bottom icons

### ISSUE THREAD

**Issue by brunorplima** [brunorplima/divino-dog-menu-app#101]
Add a number above the cart icon (slightly to the right) on the navbar showing the number of items currently in the cart.

This issue depended on the PR #110 to be done, since it is done this issue is available for start

**Comment by brunorplima** [comment]
@ericbraz  Esse issue nao precisa mais neh?! Pq criei o context pra resolver isso. Talvez mudar pra aplicar mudancas do context.

**Comment by ericbraz** [comment]
Cria o issue então pra eu prosseguir no outro
Já quero começar amanhã
