### ISSUE TITLE
Delete unnecessary file

### ISSUE THREAD

**Issue by brunorplima** [brunorplima/divino-dog-menu-app#115]
Related to #110 
Resolve this comment: https://github.com/brunorplima/divino-dog-menu-app/pull/110#issuecomment-1182659698

> delete the `hooks/useLocalStorage.ts` file

NOTE: You don't need my approval for this one. Approve it yourself and merge it

**Comment by ericbraz** [comment]
There isn't any files to delete but `hooks/useLocalStorage.ts`, right?

**Comment by brunorplima** [comment]
As far as I know you're correct
