### ISSUE TITLE
Products out of stock in menu

### ISSUE THREAD

**Issue by brunorplima** [brunorplima/divino-dog-menu-app#140]
Products that are out of stock are still being shown in the menu, allowing users to go into the product and add it to the cart.
Products that are out of stock should be shown the same way the products offered only on Fridays look on a Monday, with the difference of adding a text similar to "(Em falta)" like the text for products offered on specific days "(Sextas)".
![image](https://user-images.githubusercontent.com/29398441/227176864-995c3a46-7468-4bbc-94e2-70e03d6383f4.png)
![image](https://user-images.githubusercontent.com/29398441/227177982-a32be1ea-e907-455c-8d96-43c828fbd803.png)

**Comment by ericbraz** [comment]
@brunorplima `isAvailabloe` property is the one that indicates whether the product is in stock?

**Comment by brunorplima** [comment]
@ericbraz Yes
